# Generated by Django 2.2.4 on 2022-02-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='name',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='publisher',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
