# Generated by Django 2.2.4 on 2022-02-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0003_publisher_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='describtion',
            field=models.TextField(default='hello world !'),
        ),
    ]
