# Generated by Django 2.2.4 on 2022-02-16 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0004_book_describtion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='describtion',
            new_name='description',
        ),
    ]
