# Generated by Django 2.2.4 on 2022-02-12 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninga',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
