# Generated by Django 2.2.4 on 2022-02-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_auto_20220213_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
