# Generated by Django 2.2.4 on 2022-02-18 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Show',
            new_name='Movie',
        ),
    ]
