# Generated by Django 2.2.4 on 2022-02-18 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220218_1630'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
