# Generated by Django 2.2.4 on 2022-02-18 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
